import type {
  EdgeJourneyProgress,
  InboxItem,
  Customer360,
  Course,
  VirtualLab,
  ProgramQuestion,
  AgentControl,
} from "./edge-types.ts";

export const EDGE_JOURNEY_DATA: EdgeJourneyProgress[] = [
  {
    pillar: "engage",
    title: "Engage",
    stage: "Cisco 360 Foundations Active",
    progressPercent: 100,
    nextAction: "Verify CCO & API Center Entitlements",
    nextActionRoute: "#engage",
  },
  {
    pillar: "develop",
    title: "Develop",
    stage: "3 Certifications Active",
    progressPercent: 78,
    pviScore: 6.8,
    pviTarget: 7.5,
    pviGap: "0.7 pts to Preferred Partner",
    nextAction: "Complete SCOR 350-701 or Book CML Lab",
    nextActionRoute: "#develop",
  },
  {
    pillar: "grow",
    title: "Grow",
    stage: "$1.4M Active Pipeline",
    progressPercent: 64,
    nextAction: "Review 3 Expiring Contracts in Renewal Radar",
    nextActionRoute: "#grow",
  },
  {
    pillar: "extend",
    title: "Extend",
    stage: "Connected to Webex Hub & MCP",
    progressPercent: 50,
    nextAction: "Explore Outbound AI Webhooks",
    nextActionRoute: "#extend",
  },
];

export const INITIAL_INBOX: InboxItem[] = [
  {
    id: "inbox-1",
    type: "approval",
    title: "Action approval required: Client Discovery Brief & CRM update",
    subtitle: "Follow-up Agent · Apex Health Systems",
    description:
      "Follow-up Agent generated a discovery brief for Apex Health Systems based on their Meraki AI Ops review. Requires approval before sending email and synchronizing CRM deal stage to 'Technical Validation'.",
    source: "Agent Orchestrator / Discovery Brief",
    timestamp: "12m ago",
    freshness: "fresh",
    freshnessLabel: "Fresh · 12m ago",
    priority: "high",
    status: "unread",
    actionRequired: true,
    approvalDetails: {
      agentName: "Follow-up Agent & Discovery Brief",
      actionType: "Send Customer Email & Sync CRM Deal Stage",
      rationale:
        "Customer completed technical discovery session for 142 Meraki MX/MS devices. Solution Match confirmed 94% fit with Meraki AI Ops Dashboard.",
      impact:
        "Updates CRM Opportunity #OPP-8921 to 'Stage 3: Tech Validation'; sends calendar invite + PDF brief to IT Director at Apex Health.",
      reversibility: "Reversible",
      beforeText:
        "Stage: Stage 2 (Discovery). Brief status: Draft. No follow-up scheduled.",
      afterText:
        "Stage: Stage 3 (Tech Validation). Brief status: Delivered. Follow-up demo scheduled for Oct 2.",
      decision: "pending",
    },
  },
  {
    id: "inbox-2",
    type: "approval",
    title: "Commercial Quote Approval: EA 3.0 True Forward Add-on",
    subtitle: "Commercial Agent · Meridian Financial",
    description:
      "Commercial Agent generated a preliminary quote draft ($32,400) covering 18 Catalyst 9300 add-ons under existing Enterprise Agreement EA-771029.",
    source: "Cisco B2B GraphQL / Commercial Engine",
    timestamp: "45m ago",
    freshness: "fresh",
    freshnessLabel: "Fresh · 45m ago",
    priority: "high",
    status: "unread",
    actionRequired: true,
    approvalDetails: {
      agentName: "Commercial Agent",
      actionType: "Submit Quote Draft to 1Source & CCW",
      rationale:
        "Meridian Financial's annual True Forward reconciliation date is in 30 days. Pre-flight checks passed.",
      impact:
        "Generates Cisco CCW Estimate #EST-994012 with TD SYNNEX partner-tier discount (42.5%).",
      reversibility: "Hard gate (writes upstream)",
      beforeText:
        "Unquoted install base: 18 Catalyst 9300s (Serials FOC223401..18).",
      afterText:
        "Quote #EST-994012 linked to EA-771029. Total: $32,400 USD net.",
      decision: "pending",
    },
  },
  {
    id: "inbox-3",
    type: "renewal",
    title: "Price Protection Radar: 3 quotes expiring within 10 days",
    subtitle: "Cisco B2B Commerce Radar",
    description:
      "Quotes for Novus Logistics and Apex Health have hardware SKUs with announced price adjustments taking effect Oct 1. Convert to orders to protect margin.",
    source: "Cisco Modern Commerce API",
    timestamp: "2h ago",
    freshness: "fresh",
    freshnessLabel: "Fresh · 2h ago",
    priority: "high",
    status: "unread",
  },
  {
    id: "inbox-4",
    type: "eol",
    title: "Last Date of Support (LDoS) Alert: 6 ASA firewalls",
    subtitle: "Novus Logistics Global",
    description:
      "6 legacy ASA 5515-X security appliances hit Last Day of Support on Nov 15, 2026. Automated replacement playbook recommending Cisco Secure Firewall 1200 is ready.",
    source: "EoX Intelligence Service",
    timestamp: "5h ago",
    freshness: "fresh",
    freshnessLabel: "Verified today",
    priority: "medium",
    status: "unread",
  },
  {
    id: "inbox-5",
    type: "pvi",
    title: "PVI Milestone: Security portfolio score increased to 6.8",
    subtitle: "Cisco 360 Partner Value Index",
    description:
      "Completion of the Cisco Secure Cloud Analytics enablement path moved partner PVI from 6.3 to 6.8. Exactly 0.7 points needed to unlock Preferred Partner tier.",
    source: "Develop Analytics & PVI Tracker",
    timestamp: "1d ago",
    freshness: "fresh",
    freshnessLabel: "Fresh · Yesterday",
    priority: "medium",
    status: "read",
  },
  {
    id: "inbox-6",
    type: "learning",
    title: "AI Practice Accelerator: Live cohort enrolment open",
    subtitle: "Higher EDGEucation · Funded Seat",
    description:
      "TD SYNNEX sponsored cohort for building autonomous AI agents on Cisco infrastructure starts Oct 6. 4 partner seats remaining.",
    source: "Higher EDGEucation Catalog",
    timestamp: "1d ago",
    freshness: "fresh",
    freshnessLabel: "Verified today",
    priority: "low",
    status: "read",
  },
];

export const CUSTOMERS_DATA: Customer360[] = [
  {
    id: "cust-apex",
    company: "Apex Health Systems",
    guName: "Apex Health Enterprises Global",
    guId: "GU-849201",
    healthScore: 8.6,
    healthBand: "In Progress",
    activeEa: true,
    eaTrueForwardEstimate: "$0 (Clean Consumption)",
    lastSync: "2026-09-16 22:40 UTC",
    freshnessLabel: "Fresh · 2h ago",
    tags: ["Healthcare", "Enterprise Agreement", "Meraki Full-Stack", "Webex"],
    installBase: [
      {
        id: "ib-1",
        serial: "FOC24190281",
        pid: "C9300-48P-A",
        family: "Catalyst 9300",
        site: "Main Hospital - Campus",
        ldos: "2029-10-31",
        contract: "CON-SNTC-C930048P",
        status: "Covered",
      },
      {
        id: "ib-2",
        serial: "FOC24190282",
        pid: "C9300-48P-A",
        family: "Catalyst 9300",
        site: "Main Hospital - Campus",
        ldos: "2029-10-31",
        contract: "CON-SNTC-C930048P",
        status: "Covered",
      },
      {
        id: "ib-3",
        serial: "Q2MN-ABCD-1029",
        pid: "MX250-HW",
        family: "Meraki MX",
        site: "Regional Clinic North",
        ldos: "2028-06-30",
        contract: "LIC-MX250-ENT-3YR",
        status: "Covered",
      },
      {
        id: "ib-4",
        serial: "Q2MN-EFGH-8812",
        pid: "MS390-48UX",
        family: "Meraki MS",
        site: "Regional Clinic North",
        ldos: "2029-01-15",
        contract: "LIC-MS390-48UX-3YR",
        status: "Covered",
      },
      {
        id: "ib-5",
        serial: "FOC19283011",
        pid: "AIR-AP3802I-B-K9",
        family: "Catalyst Wireless",
        site: "Outpatient Pavilion",
        ldos: "2026-11-30",
        contract: "CON-SNTC-AIRAP380",
        status: "Expiring",
      },
    ],
    merakiDevices: 142,
    webexLicenses: 450,
    openOpportunityCards: [
      {
        id: "opp-1",
        title: "Wi-Fi 6E / Wi-Fi 7 Refresh for Outpatient Pavilion",
        category: "EoL Refresh",
        value: "$48,000",
        evidence: "24x AP3802I units reaching End of Support on Nov 30.",
        status: "New",
      },
      {
        id: "opp-2",
        title: "Cisco Spaces & Smart Workspace Sensors Add-on",
        category: "Security Attach",
        value: "$22,500",
        evidence:
          "Meraki network supports environmental sensors for hospital compliance.",
        status: "In Playbook",
      },
    ],
    playbooks: [
      {
        id: "pb-1",
        title: "Clinical Network Modernization",
        stage: "Architecture Design",
        totalTasks: 8,
        completedTasks: 6,
      },
      {
        id: "pb-2",
        title: "Annual EA True Forward Audit",
        stage: "Ready for Signature",
        totalTasks: 4,
        completedTasks: 4,
      },
    ],
  },
  {
    id: "cust-meridian",
    company: "Meridian Financial Partners",
    guName: "Meridian Financial Group Inc.",
    guId: "GU-938102",
    healthScore: 5.2,
    healthBand: "At Risk",
    activeEa: true,
    eaTrueForwardEstimate: "$32,400 (Overage Detected)",
    lastSync: "2026-09-16 18:15 UTC",
    freshnessLabel: "Fresh · 6h ago",
    tags: [
      "Financial Services",
      "Multi-Branch",
      "Catalyst Switching",
      "Security",
    ],
    installBase: [
      {
        id: "ib-6",
        serial: "FOC21049921",
        pid: "WS-C3850-48T-L",
        family: "Catalyst 3850",
        site: "Downtown Headquarters",
        ldos: "2026-10-31",
        contract: "CON-SNTC-WSC3850",
        status: "Expiring",
      },
      {
        id: "ib-7",
        serial: "FOC21049922",
        pid: "WS-C3850-48T-L",
        family: "Catalyst 3850",
        site: "Downtown Headquarters",
        ldos: "2026-10-31",
        contract: "CON-SNTC-WSC3850",
        status: "Expiring",
      },
      {
        id: "ib-8",
        serial: "FOC23810291",
        pid: "C9300-24T-A",
        family: "Catalyst 9300",
        site: "Branch 01 - Midtown",
        ldos: "2030-04-30",
        contract: "CON-SNTC-C930024T",
        status: "Covered",
      },
    ],
    merakiDevices: 18,
    webexLicenses: 180,
    openOpportunityCards: [
      {
        id: "opp-3",
        title: "Critical Catalyst 3850 to Catalyst 9300 Migration",
        category: "EoL Refresh",
        value: "$96,000",
        evidence: "Headquarters core switching enters LDoS in 44 days.",
        status: "New",
      },
      {
        id: "opp-4",
        title: "Enterprise Agreement True Forward Remediation",
        category: "EA Expansion",
        value: "$32,400",
        evidence: "18 unquoted switch ports detected in network scan.",
        status: "In Playbook",
      },
    ],
    playbooks: [
      {
        id: "pb-3",
        title: "Campus Core Refresh & Zero Trust",
        stage: "Commercial Scoping",
        totalTasks: 12,
        completedTasks: 3,
      },
    ],
  },
  {
    id: "cust-novus",
    company: "Novus Logistics Global",
    guName: "Novus Supply Chain Corp",
    guId: "GU-472190",
    healthScore: 3.8,
    healthBand: "Stalled",
    activeEa: false,
    eaTrueForwardEstimate: "N/A (No Active EA)",
    lastSync: "2026-09-15 08:30 UTC",
    freshnessLabel: "Aging · 1d ago",
    tags: ["Logistics", "Distribution", "Legacy Hardware", "Needs Assessment"],
    installBase: [
      {
        id: "ib-9",
        serial: "JMX19028101",
        pid: "ASA5515-K9",
        family: "Cisco ASA",
        site: "Warehouse Hub - Dallas",
        ldos: "2026-11-15",
        contract: "Expired",
        status: "Uncovered",
      },
      {
        id: "ib-10",
        serial: "JMX19028102",
        pid: "ASA5515-K9",
        family: "Cisco ASA",
        site: "Warehouse Hub - Chicago",
        ldos: "2026-11-15",
        contract: "Expired",
        status: "Uncovered",
      },
      {
        id: "ib-11",
        serial: "Q2MN-WXYZ-7701",
        pid: "MR44-HW",
        family: "Meraki Wireless",
        site: "Warehouse Hub - Dallas",
        ldos: "2028-12-31",
        contract: "LIC-ENT-3YR",
        status: "Covered",
      },
    ],
    merakiDevices: 64,
    webexLicenses: 25,
    openOpportunityCards: [
      {
        id: "opp-5",
        title: "Urgent ASA Replacement: Cisco Secure Firewall 1200",
        category: "Security Attach",
        value: "$38,400",
        evidence: "Firewalls unprotected and past hardware support.",
        status: "New",
      },
      {
        id: "opp-6",
        title: "Warehouse Ruggedized Wi-Fi Expansion",
        category: "Renewal",
        value: "$19,200",
        evidence: "Meraki cloud license renewal due in 60 days.",
        status: "New",
      },
    ],
    playbooks: [
      {
        id: "pb-4",
        title: "Security Perimeter Hardening",
        stage: "Discovery Call Pending",
        totalTasks: 6,
        completedTasks: 1,
      },
    ],
  },
];

export const COURSES_DATA: Course[] = [
  {
    id: "course-1",
    title: "Cisco 360 Partner Value Index (PVI) Foundations & Strategy",
    slug: "cisco-360-pvi-foundations",
    pillar: "Engage",
    portfolio: "Services",
    format: "Self-paced",
    registrationModel: "quick",
    coursePrice: "Free",
    eventPrice: "Free",
    duration: "2 hours",
    pviDimension: "Program Foundations",
    pviImpact: "+0.3 PVI baseline score",
    description:
      "Master the mechanics of Cisco 360, understand the 4 PVI capability weightings, and build your practice roadmap toward Preferred Partner status.",
    isRegistered: true,
    classes: [
      {
        id: "cls-1",
        date: "Instant Access (On-Demand)",
        modality: "Self-paced",
        instructor: "TD SYNNEX Practice Leads",
        seatsLeft: 999,
        classPrice: "Free",
      },
    ],
  },
  {
    id: "course-2",
    title:
      "Implementing and Operating Cisco Security Core Technologies (SCOR 350-701)",
    slug: "scor-350-701-core",
    pillar: "Develop",
    portfolio: "Security",
    format: "ILT",
    registrationModel: "order",
    coursePrice: "Free (Catalog info)",
    eventPrice: "$1,999.00",
    duration: "5 days (Virtual ILT)",
    pviDimension: "Security Specialization",
    pviImpact: "+0.5 PVI Security Capability",
    description:
      "Comprehensive preparation for the Cisco CCNP Security and CCIE Security certifications. Hands-on virtual labs with Cisco Secure Firewall, Duo, and Umbrella.",
    isRegistered: false,
    classes: [
      {
        id: "cls-2",
        date: "Oct 12 – Oct 16, 2026",
        modality: "Instructor-led",
        instructor: "Markus Vance (CCIE #29104)",
        seatsLeft: 4,
        classPrice: "$1,999.00",
      },
      {
        id: "cls-3",
        date: "Nov 09 – Nov 13, 2026",
        modality: "Instructor-led",
        instructor: "Sarah Chen (CCIE #41920)",
        seatsLeft: 8,
        classPrice: "$1,999.00",
      },
    ],
  },
  {
    id: "course-3",
    title:
      "AI Practice Accelerator: Agentic Architectures on Cisco Infrastructure",
    slug: "ai-practice-accelerator-agents",
    pillar: "Develop",
    portfolio: "Cloud and AI Infrastructure",
    format: "Webinar",
    registrationModel: "funded",
    coursePrice: "Funded ($0 partner cost)",
    eventPrice: "TD SYNNEX Sponsored",
    duration: "3 weeks (cohort-based)",
    pviDimension: "AI & Innovation Specialization",
    pviImpact: "+0.8 PVI Cloud/AI Capability",
    description:
      "Exclusive TD SYNNEX partner accelerator cohort. Build hands-on LLM agents, integrate LiveKit voice/video pipelines, and orchestrate with Cisco UCS and Nexus AI Fabrics.",
    isRegistered: false,
    classes: [
      {
        id: "cls-4",
        date: "Starts Oct 06, 2026 (Weekly Tue/Thu)",
        modality: "Webinar",
        instructor: "Ruben Dedman & AI Squad",
        seatsLeft: 2,
        classPrice: "Funded ($0)",
      },
    ],
  },
  {
    id: "course-4",
    title: "Meraki Full-Stack Sales & Architectural Masterclass",
    slug: "meraki-full-stack-masterclass",
    pillar: "Grow",
    portfolio: "Networking",
    format: "Video",
    registrationModel: "none",
    coursePrice: "Free",
    eventPrice: "Free",
    duration: "3.5 hours",
    pviDimension: "Networking Specialization",
    pviImpact: "+0.4 PVI Networking Capability",
    description:
      "Learn how to pitch, design, and close Meraki full-stack solutions across switching, Wi-Fi 6E/7, security appliances, and environmental IoT sensors.",
    isRegistered: true,
    classes: [
      {
        id: "cls-5",
        date: "Instant Access (Video Library)",
        modality: "Video",
        instructor: "TD SYNNEX Meraki BDE Team",
        seatsLeft: 999,
        classPrice: "Free",
      },
    ],
  },
  {
    id: "course-5",
    title: "Cisco Enterprise Agreement 3.0 & True Forward Commercial Mastery",
    slug: "cisco-ea-3-commercial-mastery",
    pillar: "Grow",
    portfolio: "Services",
    format: "SCORM",
    registrationModel: "quick",
    coursePrice: "Free",
    eventPrice: "Free",
    duration: "90 min",
    pviDimension: "Commercial & Lifecycle",
    pviImpact: "+0.3 PVI Services Capability",
    description:
      "Understand EA 3.0 multi-suite contracting, consumption metrics, partner markup rules, and how to avoid customer True Forward surprises.",
    isRegistered: false,
    classes: [
      {
        id: "cls-6",
        date: "Instant Interactive SCORM module",
        modality: "SCORM",
        instructor: "TD SYNNEX Commercial Desk",
        seatsLeft: 999,
        classPrice: "Free",
      },
    ],
  },
  {
    id: "course-6",
    title: "Automating Cisco Operations with Python & Cisco B2B GraphQL APIs",
    slug: "automating-cisco-modern-graphql",
    pillar: "Extend",
    portfolio: "Cloud and AI Infrastructure",
    format: "ILT",
    registrationModel: "quick",
    coursePrice: "Free",
    eventPrice: "Free",
    duration: "4 hours",
    pviDimension: "Developer & Programmability",
    pviImpact: "+0.4 PVI Innovation Score",
    description:
      "Hands-on guide to using Cisco's Modern B2B GraphQL APIs. Build automated quote pre-flight checks, order status webhooks, and integrate with MCP agents.",
    isRegistered: false,
    classes: [
      {
        id: "cls-7",
        date: "Oct 21, 2026 · 1:00 PM EST",
        modality: "Webinar",
        instructor: "TD SYNNEX Solutions Engineering",
        seatsLeft: 16,
        classPrice: "Free",
      },
    ],
  },
];

export const VIRTUAL_LABS_DATA: VirtualLab[] = [
  {
    id: "lab-cml-1",
    title: "Cisco Modeling Labs: Catalyst 9000 & 8000 Edge Automation",
    topology:
      "Dual Catalyst 9300 + Catalyst 8000V SD-WAN + Linux Automation Host",
    category: "Networking & Programmability",
    devices: ["2x IOS-XE 17.9", "1x C8000v", "1x Ubuntu Testbed"],
    durationHours: 3,
    state: "running",
    serverStatus: "Active",
    idleMinutesRemaining: 24,
    scheduledTime: "Today · 2:00 PM – 5:00 PM",
    consoleUrl: "https://cml.labs.tdsynnex.internal/lab-9921",
  },
  {
    id: "lab-cml-2",
    title: "Cisco Secure Firewall Threat Defense (FTD) High Availability",
    topology:
      "2x FTDv + FMCv (Firewall Management Center) + DMZ traffic generator",
    category: "Security",
    devices: ["2x FTDv 7.4", "1x FMCv 7.4", "Traffic Gen"],
    durationHours: 4,
    state: "stopped",
    serverStatus: "Off (Saved)",
    scheduledTime: "Available on-demand (boots in 12 min)",
  },
  {
    id: "lab-cml-3",
    title: "Nexus Dashboard Fabric Controller (NDFC) & VXLAN EVPN",
    topology: "Spine-Leaf Topology with 4x Nexus 9300v + NDFC Controller",
    category: "Data Center & AI Fabrics",
    devices: ["4x NX-OS 9.3v", "1x NDFC 12.1"],
    durationHours: 4,
    state: "stopped",
    serverStatus: "Off (Saved)",
    scheduledTime: "Available on-demand (boots in 15 min)",
  },
];

export const PROGRAM_QUESTIONS_DATA: ProgramQuestion[] = [
  {
    id: "pq-1",
    question:
      "How is the Partner Value Index (PVI) calculated under the Cisco 360 Partner Program?",
    category: "Program Mechanics",
    answer:
      "The Cisco 360 Partner Value Index (PVI) is a 10-point weighted index calculated across four foundational pillars: Foundational Capability (45%), Practice Breadth (25%), Specialization Depth (20%), and Customer Lifecycle Excellence (10%). Partners maintaining a score >= 7.5 unlock Preferred Partner benefits, exclusive rebates, and priority MDF allocations. The official score is computed and verified by Cisco inside the PXP portal.",
    citations: [
      {
        pillText: "Cisco 360 Partner Framework §3.4",
        source: "Cisco Systems Global Partner Organization (Jan 2026)",
        passage:
          "PVI replaces legacy tiers with continuous performance indexing. Dimensions include Capability, Breadth, Specialization, and Lifecycle with category weights 45/25/20/10.",
      },
      {
        pillText: "TD SYNNEX PVI Strategy Guide",
        source: "TD SYNNEX Cisco Practice (Sep 2026)",
        passage:
          "Our role-based learning paths in the Develop pillar are mapped directly to PVI capabilities, allowing partners to close score gaps predictably.",
      },
    ],
    verifiedDate: "2026-09-16",
    freshness: "Verified Sep 2026",
  },
  {
    id: "pq-2",
    question:
      "What are the rules and requirements for Cisco EA 3.0 True Forward reconciliations?",
    category: "Commerce & EA",
    answer:
      "Under Cisco Enterprise Agreement 3.0, customers can deploy software and licenses dynamically throughout the contract term. Annually on the True Forward date, actual consumption is audited against purchased entitlements. If consumption exceeds entitlements, a non-retroactive True Forward quote is generated covering only the remaining contract term at the partner's contractual rate card. No back-billing or penalties are assessed for mid-term overage.",
    citations: [
      {
        pillText: "Cisco B2B Commerce Bible §7.2",
        source: "Cisco Commercial Operations (Apr 2026)",
        passage:
          "True Forward is forward-looking. Value = (Consumed Quantity - Entitled Quantity) * Net Unit Rate * (Remaining Months / 12). Negative values do not produce credits.",
      },
      {
        pillText: "TD SYNNEX 1Source EA Guide",
        source: "PartnerFirst Commercial Desk",
        passage:
          "Partners must configure customer markup in EDGE Beacon / Revolution to ensure commercial True Forward estimates display accurately.",
      },
    ],
    verifiedDate: "2026-09-15",
    freshness: "Verified Sep 2026",
  },
  {
    id: "pq-3",
    question: "What is the onboarding policy for Cisco B2B Commerce APIs?",
    category: "API & Integrations",
    answer:
      "Since April 2026, Cisco Modern GraphQL APIs are the only authorized path for new partner integrations covering catalog, pricing, estimates, quotes, orders, and subscriptions. Legacy RosettaNet PIPs, EDI, and REST services are closed to new onboarding. API credentials must be authenticated via Cisco cloudsso OAuth2 client credentials or delegated user tokens.",
    citations: [
      {
        pillText: "Cisco Modern APIs Newsletter NL-2026-04",
        source: "Cisco IT B2B Architecture (Apr 2026)",
        passage:
          "Modern APIs (GraphQL) are mandatory for all new commerce onboarding. Existing RosettaNet endpoints remain in run-only maintenance without feature additions.",
      },
    ],
    verifiedDate: "2026-09-14",
    freshness: "Verified Sep 2026",
  },
];

export const AGENT_CONTROLS_DATA: AgentControl[] = [
  {
    id: "ag-account",
    name: "Account Context Agent",
    role: "Graph & CRM Intelligence",
    autonomy: "Autonomous",
    runsTotal: 482,
    approvalRate: "100%",
    lastRunOutcome: "Loaded customer telemetry & GU profile for Apex Health",
    isPaused: false,
    allowedTools: ["Client 360 Graph", "Cisco Smart Accounts", "CRM Read"],
  },
  {
    id: "ag-opportunity",
    name: "Opportunity Agent",
    role: "Install Base & EoX Radar",
    autonomy: "Autonomous",
    runsTotal: 341,
    approvalRate: "100%",
    lastRunOutcome: "Ranked 6 EoL replacement opportunities",
    isPaused: false,
    allowedTools: ["Install Base DB", "Support EoX API", "Contract Search"],
  },
  {
    id: "ag-solution",
    name: "Solution Match Agent",
    role: "Catalog Recommendation",
    autonomy: "Autonomous",
    runsTotal: 819,
    approvalRate: "98.4%",
    lastRunOutcome: "Matched Meraki AI Ops with 94% confidence",
    isPaused: false,
    allowedTools: [
      "Solution Catalog (12)",
      "Use Case Atlas (375)",
      "Prerequisite Validator",
    ],
  },
  {
    id: "ag-commercial",
    name: "Commercial Agent",
    role: "Pricing & Quote Synthesis",
    autonomy: "Supervised",
    runsTotal: 194,
    approvalRate: "94.2%",
    lastRunOutcome: "Generated estimate #EST-994012; awaiting human approval",
    isPaused: false,
    allowedTools: ["Cisco B2B GraphQL", "TD SYNNEX P&A", "CCW Quoting"],
  },
  {
    id: "ag-brief",
    name: "Discovery Brief Agent",
    role: "Executive Brief Creation",
    autonomy: "Supervised",
    runsTotal: 212,
    approvalRate: "96.5%",
    lastRunOutcome: "Created draft brief for Apex Health Systems",
    isPaused: false,
    allowedTools: ["Canvas Generator", "Markdown Exporter", "Client Summary"],
  },
  {
    id: "ag-followup",
    name: "Follow-up Agent",
    role: "Communication & CRM Sync",
    autonomy: "Supervised",
    runsTotal: 156,
    approvalRate: "91.8%",
    lastRunOutcome: "Pending review: email draft & CRM sync for Apex Health",
    isPaused: false,
    allowedTools: ["Calendar Inviter", "Email Drafter", "CRM Stage Writer"],
  },
  {
    id: "ag-navigator",
    name: "Program Navigator",
    role: "Cisco 360 Knowledge & Citations",
    autonomy: "Autonomous",
    runsTotal: 1042,
    approvalRate: "99.8%",
    lastRunOutcome: "Answered PVI weighting inquiry with passage citations",
    isPaused: false,
    allowedTools: [
      "Permission-aware RAG",
      "Cisco 360 Docs",
      "Citation Builder",
    ],
  },
];
