import {
  createElement,
  ArrowRight,
  ChevronRight,
  Menu,
  X,
  PanelLeftClose,
  Compass,
  LayoutGrid,
  Bookmark,
  GraduationCap,
  Layers,
  MessageSquare,
  CircleHelp,
  Network,
  Workflow,
  Plug,
  BookOpen,
  Phone,
  Activity,
  ShieldCheck,
  Server,
  LockKeyhole,
  Target,
  Building2,
  Video,
  Lightbulb,
  Search,
  ExternalLink,
  Plus,
  Check,
  Copy,
  Download,
  FileText,
  Trash2,
  Home,
  TrendingUp,
  Share2,
  Sliders,
  Terminal,
  Clock,
  AlertTriangle,
  User,
  Inbox,
  Calendar,
  Sparkles,
  CheckCircle2,
  AlertCircle,
  Cpu,
  RefreshCw,
  Eye,
  Play,
  Bell,
  Command,
} from "lucide";
import type { IconNode } from "lucide";

const icons: Record<string, IconNode> = {
  arrow: ArrowRight,
  chevron: ChevronRight,
  menu: Menu,
  close: X,
  panel: PanelLeftClose,
  compass: Compass,
  grid: LayoutGrid,
  bookmark: Bookmark,
  graduation: GraduationCap,
  layers: Layers,
  message: MessageSquare,
  help: CircleHelp,
  network: Network,
  workflow: Workflow,
  plug: Plug,
  book: BookOpen,
  phone: Phone,
  activity: Activity,
  shield: ShieldCheck,
  server: Server,
  lock: LockKeyhole,
  target: Target,
  building: Building2,
  video: Video,
  lightbulb: Lightbulb,
  search: Search,
  external: ExternalLink,
  plus: Plus,
  check: Check,
  copy: Copy,
  download: Download,
  file: FileText,
  trash: Trash2,
  home: Home,
  growth: TrendingUp,
  share: Share2,
  sliders: Sliders,
  terminal: Terminal,
  clock: Clock,
  alert: AlertTriangle,
  user: User,
  inbox: Inbox,
  calendar: Calendar,
  sparkles: Sparkles,
  checkCircle: CheckCircle2,
  alertCircle: AlertCircle,
  cpu: Cpu,
  refresh: RefreshCw,
  eye: Eye,
  play: Play,
  bell: Bell,
  command: Command,
};

export const icon = (name = "compass") =>
  createElement(icons[name] ?? Compass, {
    class: "icon",
    "aria-hidden": "true",
    "stroke-width": 1.75,
  }).outerHTML;
